---
- name: Reload Systemd
  become: yes
  command: systemctl daemon-reload

- name: Remove old o2r-finder container
  become: yes
  notify: Wait for o2r-finder to start up
  docker_container:
    name: "{{finder_role.container.name}}"
    state: absent

- name: Restart o2r-finder
  become: yes
  notify: Wait for o2r-finder to start up
  service: name=o2r-finder state=restarted

- name: Wait for o2r-finder to start up
  pause: seconds=10
